import { Community, Group } from '../types';

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: 'comm_jee',
    name: 'JEE Advanced 2027',
    slug: 'jee-advanced-2027',
    description: 'Premier academic cohort for Physics, Chemistry & Advanced Mathematics.',
    avatarUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=150&auto=format&fit=crop&q=80',
    ownerId: 'system_owner',
    adminIds: ['system_owner'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'comm_algo',
    name: 'Algorithms & Systems Guild',
    slug: 'algorithms-guild',
    description: 'Competitive programming, distributed systems, Linux kernel & architecture.',
    avatarUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&auto=format&fit=crop&q=80',
    ownerId: 'system_owner',
    adminIds: ['system_owner'],
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'comm_med',
    name: 'Pre-Med & USMLE Alliance',
    slug: 'premed-usmle',
    description: 'Pathology, pharmacology, high-yield clinical rotations & anatomy.',
    avatarUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=150&auto=format&fit=crop&q=80',
    ownerId: 'system_owner',
    adminIds: ['system_owner'],
    createdAt: '2026-01-12T00:00:00Z',
  },
];

export const INITIAL_GROUPS: Group[] = [
  // JEE Advanced Sub-groups
  {
    id: 'grp_jee_announcements',
    communityId: 'comm_jee',
    name: 'Announcements',
    description: 'Official community broadcasts, exam test series schedules, and syllabus updates.',
    avatarUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=150&auto=format&fit=crop&q=80',
    isAnnouncementGroup: true,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'admins_only',
      editGroupInfo: 'admins_only',
      addMembers: 'admins_only',
    },
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'grp_jee_physics',
    communityId: 'comm_jee',
    name: 'Rotational & Classical Mechanics',
    description: 'Pathfinder, Irodov, and Olympiad problem derivations.',
    avatarUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=150&auto=format&fit=crop&q=80',
    isAnnouncementGroup: false,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'all',
      editGroupInfo: 'admins_only',
      addMembers: 'all',
    },
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'grp_jee_chem',
    communityId: 'comm_jee',
    name: 'Organic Reaction Mechanisms',
    description: 'Clayden synthesis, stereochemistry & reagent problem solving.',
    avatarUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=150&auto=format&fit=crop&q=80',
    isAnnouncementGroup: false,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'all',
      editGroupInfo: 'admins_only',
      addMembers: 'all',
    },
    createdAt: '2026-01-03T00:00:00Z',
  },

  // Algorithms Sub-groups
  {
    id: 'grp_algo_announcements',
    communityId: 'comm_algo',
    name: 'Guild Announcements',
    description: 'Contest reminders, ICPC qualifiers, and mock interviews.',
    isAnnouncementGroup: true,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'admins_only',
      editGroupInfo: 'admins_only',
      addMembers: 'admins_only',
    },
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'grp_algo_distributed',
    communityId: 'comm_algo',
    name: 'Distributed Systems & Raft',
    description: 'Consensus protocols, LSM trees, MIT 6.824 labs, and concurrent architectures.',
    avatarUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=150&auto=format&fit=crop&q=80',
    isAnnouncementGroup: false,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'all',
      editGroupInfo: 'admins_only',
      addMembers: 'all',
    },
    createdAt: '2026-01-06T00:00:00Z',
  },
  {
    id: 'grp_algo_dp',
    communityId: 'comm_algo',
    name: 'Hard Dynamic Programming',
    description: 'Digit DP, Tree DP, SOS DP, Convex Hull trick and game theory.',
    avatarUrl: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=150&auto=format&fit=crop&q=80',
    isAnnouncementGroup: false,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'all',
      editGroupInfo: 'admins_only',
      addMembers: 'all',
    },
    createdAt: '2026-01-08T00:00:00Z',
  },

  // Pre-Med Sub-groups
  {
    id: 'grp_med_announcements',
    communityId: 'comm_med',
    name: 'Alliance Announcements',
    description: 'High-yield decks, NBME dates, and Step 1 review schedules.',
    isAnnouncementGroup: true,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'admins_only',
      editGroupInfo: 'admins_only',
      addMembers: 'admins_only',
    },
    createdAt: '2026-01-12T00:00:00Z',
  },
  {
    id: 'grp_med_pathology',
    communityId: 'comm_med',
    name: 'Renal & Cardiovascular Pathology',
    description: 'Case studies, histological slides, and diagnostic algorithms.',
    avatarUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=150&auto=format&fit=crop&q=80',
    isAnnouncementGroup: false,
    ownerId: 'system_owner',
    memberIds: [],
    adminIds: ['system_owner'],
    permissions: {
      sendMessages: 'all',
      editGroupInfo: 'admins_only',
      addMembers: 'all',
    },
    createdAt: '2026-01-15T00:00:00Z',
  },
];
